### ISSUE TITLE
Configuring single sub-module not working

### ISSUE THREAD

**Issue by penrillian-barry** [sivakumar-kailasam/codeclimate-checkstyle#1]
I wanted to alter the default regex used in the MemberName sub-module ("^[a-z][a-z0-9][a-zA-Z0-9]*$"). The regex I wanted to use was "^[a-z][a-zA-Z0-9]*$". I created the following checkstyle.xml file:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="severity" value="warning"/>
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="TreeWalker">
        <module name="MemberName">
            <property name="format" value="^[a-z][a-zA-Z0-9]*$"/>
            <message key="name.invalidPattern"
                     value="Member name ''{0}'' must match pattern ''{1}''."/>
        </module>
    </module>
</module>
```

However, this change to the regex was ignored. The only way I could get this change to be observed was to add the entire checkstyle.xml from [here](https://github.com/sivakumar-kailasam/codeclimate-checkstyle/blob/master/config/codeclimate_checkstyle.xml), and change the regex in that file.

Is this expected?

**Comment by sivakumar-kailasam** [comment]
@penrillian-barry if you've defined the path to your config, it should've been used. Refer to https://github.com/sivakumar-kailasam/codeclimate-checkstyle#sample-codeclimateyml-configuration

**Comment by penrillian-barry** [comment]
@sivakumar-kailasam yes, I added the path and it didn't work:

```
engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    config: "checkstyle.xml"
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.SummaryJavadocCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.ParameterNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.LocalVariableNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.whitespace.EmptyLineSeparatorCheck:
        enabled: false
    channel: "beta"
  pmd:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths:
- "**/test/**/*"

```
