### ISSUE TITLE
Panic in checkstyle.rb

### ISSUE THREAD

**Issue by joa** [sivakumar-kailasam/codeclimate-checkstyle#13]
Running codeclimate yields the following exception for me:
```
/usr/src/app/lib/cc/engine/checkstyle.rb:89:in `rescue in print_issue': No description available for com.puppycraw (KeyError)
	from /usr/src/app/lib/cc/engine/checkstyle.rb:85:in `print_issue'
	from /usr/src/app/lib/cc/engine/checkstyle.rb:31:in `block in run'
	from /usr/local/bundle/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
	from /usr/local/bundle/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
	from /usr/local/bundle/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
	from /usr/src/app/lib/cc/engine/checkstyle.rb:30:in `run'
	from /usr/src/app/bin/codeclimate-checkstyle:16:in `<main>'
```

Codeclimate is invoked using the following command:

```bash
docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f json -e checkstyle:beta -e fixme > codeclimate.json
```

### .codeclimate.yml
```yaml
engines:
  fixme:
    enabled: true
  checkstyle:
    enabled: true
    channel: beta
    config: "checkstyle.xml"

ratings:
  paths:
  - "**.java"

exclude_paths:
- "**/test/**/*"
```

### checkstyle.xml
See https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

Let me know if you need any additional information and keep up the good work!
